### ISSUE TITLE
Suppress multiple repeated activity into one ( per pr )

### ISSUE THREAD

**Issue by rvraghav93** [gitterHQ/services#41]
Multiple activity per PR ( especially successive pushing to the branch for updating / rebasing etc ) could be suppressed into one activity feed per PR ( or issue ) that would display the latest activity and later expand to multiple activities if needed by clicking on it.

**Comment by trevorah** [comment]
Yeah, batching up messages would help filter out noise. :+1:

**Comment by MadLittleMods** [comment]
Duplicate of https://github.com/gitterHQ/gitter/issues/480 as this is more of a UI issue, https://github.com/gitterHQ/gitter/issues/480 but might require an extra related field or something here to link them.
