### ISSUE TITLE
Coub embed integration

### ISSUE THREAD

**Issue by TheJaredWilcurt** [gitterHQ/services#67]
Detect these URL's in chat: http://coub.com/view/8k212

and convert them to embedded versions:

```
<iframe src="//coub.com/embed/8k212?muted=0&autostart=0&originalSize=0&startWithHD=0"
  allowfullscreen="true" frameborder="0" width="100%" height="360"></iframe>
```

* http://coub.com/view/5ueub

**Comment by MadLittleMods** [comment]
@TheJaredWilcurt Sorry, I thought you actually wanting an integration that shows up in the Activity panel based off [your comment "Request: Coub embed integration"](https://gitter.im/gitterHQ/gitter?at=56e4b4acf892e2e611ee6cc2). But it looks like you want a rich embed in chat messages.

We currently use [iframely](https://iframely.com/) and have done some work to maybe switch to [embedly](http://embed.ly/). It would be best to add requests there or with Coub if action is needed there.

**Comment by TheJaredWilcurt** [comment]
@MadLittleMods Iframely supports coub, but it doesn't embed in chat:

https://iframely.com/oembed2#quick-example-coub-viral-videos
