### ISSUE TITLE
Activity feed has stopped updating

### ISSUE THREAD

**Issue by N8Solutions** [gitterHQ/services#87]
No matter what room I am viewing the activity feed is **NOT** showing anything past **January 26th**. I have logged in from different browsers on the same computer, tried using different computers, even logging in using my iPad, all with the same result.

**Comment by mydigitalself** [comment]
Yip, sorry we had some infrastructure issues last week and had to do some emergency open heart surgery to fix. As a result, incoming webhooks were disabled for a while.
