### ISSUE TITLE
GitHub integration is not working

### ISSUE THREAD

**Issue by egordorichev** [gitterHQ/services#92]
I've added github integration to my chat room, but it doesn't do anything. 
https://gitter.im/last-try/Lobby
Thanks.

**Comment by MadLittleMods** [comment]
Hey @egordorichev,

Can you expand on what you mean by not working? I assume it isn't adding events to the stream as you expect.

On GitHub, check the webhooks on the repo you added an integration for, `https://github.com/<your-repo>/services/settings/hooks` - You can add it manually from that page.

On Gitter, when you view settings -> Integrations, do you see a GitHub entry?

**Comment by egordorichev** [comment]
@MadLittleMods, i'm so sorry. I just did not find the notifications button. Any way, the interface is a bit strange :) I found the dark mode only after two years using gitter.

**Comment by MadLittleMods** [comment]
@egordorichev Dark mode/theme was only added on on 2017-11-17, https://github.com/gitterHQ/gitter/issues/1467
